import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { Toaster, toast } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "CodeFusion - Showcase. Collaborate. Innovate.",
    template: "%s - CodeFusion",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background text-muted-foreground antialiased dark`}>
        <Header />
        {children}
        <Footer />
        <Toaster richColors toastOptions={{
          className: 'bg-background border-border text-muted-foreground'
        }} />
      </body>
    </html>
  );
}
